### ISSUE TITLE
关于横屏摄像头检测

### ISSUE THREAD

**Issue by morel17** [aitsuki/LivenessDetectionSample#1]
问下如果是横屏的话需要怎么调整才能够识别呢

**Comment by aitsuki** [comment]
把activity设置为横屏就行了。
但是横屏检测会存在摄像机角度问题，因为此时摄像头和人脸不在一条线上，所以检测出来的人脸旋转角度就不正确，需要手动矫正。 例如正脸检测通过时记录此时的人脸角度，在其他检测步骤时根据这个角度偏转。

其实竖屏也会有一些影响，有些前置摄像头偏左或偏右，不过问题不大。

**Comment by aitsuki** [comment]
更新了一版，demo支持横屏了

**Comment by morel17** [comment]
感谢，这几天摸熟悉了后感觉camerax+mlkit功能非常不错的👍
