### ISSUE TITLE
一直提示存在多个人脸

### ISSUE THREAD

**Issue by yueying0083** [aitsuki/LivenessDetectionSample#3]
传给FaceAnalyzer的是整个摄像头拍摄区域， 而不只是框住的区域

**Comment by aitsuki** [comment]
提示多个人脸是正常的，如果不需要这项检测可以自己去掉 https://github.com/aitsuki/LivenessDetectionSample/blob/0f730acc4d3e5750995ab4992424923b5167ab29/app/src/main/java/com/example/liveness/core/LivenessDetector.kt#L53

**Comment by aitsuki** [comment]
另外传给摄像头的区域是根据CameraX的Preview控件大小来的，调整这个大小即可控制拍摄区域。需要注意的是这个区域也不是完全精确的，和摄像头的位置也有一些关系，例如有些手机的前置摄像头在左侧或者右侧都会导致区域发生偏移，而处于摄像头处于中间的手机表现就比较好。

**Comment by yueying0083** [comment]
传给mlkit分析的是矩形，而圆形区域是view层面的剪切，存在被遮挡之后误报的问题

**Comment by aitsuki** [comment]
确实会存在这个问题，比如第二个人脸在矩形内但是在裁剪区域外，也会出现提示多个人脸的情况，实际上可视区域只有一张人脸。解决方案也挺简单，将检测到的人脸根据坐标过滤一下就好了。
