### ISSUE TITLE
7.1.2系统报错

### ISSUE THREAD

**Issue by xing-chch** [aitsuki/LivenessDetectionSample#5]
你好，我在用7.1.2系统上，摄像头打开失败，跟踪源码，执行到这里返回了
if (mCameraProvider == null) {
            Log.d(TAG, "CameraProvider is not ready.");
            return null;
        }

**Comment by aitsuki** [comment]
可能是CameraX的bug，能不能在你的设备上单独跑一下camerax的demo开有没有问题。
https://github.com/android/camera-samples/tree/master/CameraX-MLKit

**Comment by xing-chch** [comment]
这个单独的camerax的demo预览正常

**Comment by xing-chch** [comment]
cameraController = LifecycleCameraController(this)
this换成baseContext就好了

**Comment by xing-chch** [comment]
//        cameraController.cameraSelector = CameraSelector.DEFAULT_FRONT_CAMERA
这段代码导致

**Comment by aitsuki** [comment]
那估计是 controller 的原因了。 现在最新的Compose版本没有使用cameraController，应该没问题吧。
你把代码回退几个版本也是没有使用controller的，都可以试试。

**Comment by xing-chch** [comment]
谢谢
